#!/bin/bash

bash -c 'cat > /etc/systemd/system/freqtrade.service' << 'EOL'
Description=freqtrade service
After=network.target

[Service]
ExecStart=/bin/bash -c "cd /root/freqtrade ; source .env/bin/activate ; freqtrade trade --strategy freqtrade"
Restart=always
StandardError=append:/var/log/freqtrade.log

[Install]
WantedBy=multi-user.target
EOL

systemctl daemon-reload
systemctl enable freqtrade.service
