#!/bin/bash

echo setting variables
configfile=/usr/local/$botname/config.json

echo saving current configuration
stake_currency=$(grep '^ *"stake_currency":' $configfile | awk '{ print $2 }' | sed -e 's/,$//' -e 's/^"//' -e 's/"$//')
display_currency=$(grep '^ *"fiat_display_currency":' $configfile | awk '{ print $2 }' | sed -e 's/,$//' -e 's/^"//' -e 's/"$//')
stake_amount=$(grep '^ *"stake_amount":' $configfile | awk '{ print $2 }' | sed -e 's/,$//' -e 's/^"//' -e 's/"$//')
max_open_trades=$(grep '^ *"max_open_trades":' $configfile | awk '{ print $2 }' | sed -e 's/,$//' -e 's/^"//' -e 's/"$//')
exchange_name=$(grep '^ *"name":' $configfile | awk '{ print $2 }' | sed -e 's/,$//' -e 's/^"//' -e 's/"$//')
exchange_key=$(grep '^ *"key":' $configfile | awk '{ print $2 }' | sed -e 's/,$//' -e 's/^"//' -e 's/"$//')
exchange_secret=$(grep '^ *"secret":' $configfile | awk '{ print $2 }' | sed -e 's/,$//' -e 's/^"//' -e 's/"$//')
telegram_token=$(grep '^ *"token":' $configfile | awk '{ print $2 }' | sed -e 's/,$//' -e 's/^"//' -e 's/"$//')
telegram_chatid=$(grep '^ *"chat_id":' $configfile | awk '{ print $2 }' | sed -e 's/,$//' -e 's/^"//' -e 's/"$//')
webuser=$(grep '^ *"username":' $configfile | awk '{ print $2 }' | sed -e 's/,$//' -e 's/^"//' -e 's/"$//')
webpass=$(grep '^ *"password":' $configfile | awk '{ print $2 }' | sed -e 's/,$//' -e 's/^"//' -e 's/"$//')
webport=$(grep '^ *"listen_port":' $configfile | awk '{ print $2 }' | sed -e 's/,$//' -e 's/^"//' -e 's/"$//')
ipaddress=$(grep '^ *"listen_ip_address":' $configfile | awk '{ print $2 }' | sed -e 's/,$//' -e 's/^"//' -e 's/"$//')
secretkey=$(grep '^ *"jwt_secret_key":' $configfile | awk '{ print $2 }' | sed -e 's/,$//' -e 's/^"//' -e 's/"$//')

echo
echo Stake Curency: $stake_currency
echo Display Currency: $display_currency
echo Stake Amount: $stake_amount
echo Max Open Trades: $max_open_trades
echo Exchange Name: $exchange_name
echo Exchange Key: $exchange_key
echo Exchange Secret: $exchange_secret
echo Telegram Token: $telegram_token
echo Telegram Chat ID: $telegram_chatid
echo FreqUI Username: $webuser
echo FreqUI Password: $webpass
echo Listen Port: $webport
echo Listen IP Address: $ipaddress
echo Secret Key: $secretkey
echo

echo stopping freqtrade
systemctl stop $botname.service

echo removing old configuration
rm $configfile

echo downloading updated configuration
wget -q https://raw.githubusercontent.com/aristosv/freqtrade/main/install_config --output-document="$configfile"

echo writing saved configuration
sed -i "s/\$stake_currency/$stake_currency/g" $configfile
sed -i "s/\$display_currency/$display_currency/g" $configfile
sed -i "s/\$stake_amount/$stake_amount/g" $configfile
sed -i "s/\$max_open_trades/$max_open_trades/g" $configfile
sed -i "s/\$exchange_name/$exchange_name/g" $configfile
sed -i "s/\$exchange_key/$exchange_key/g" $configfile
sed -i "s/\$exchange_secret/$exchange_secret/g" $configfile
sed -i "s/\$telegram_token/$telegram_token/g" $configfile
sed -i "s/\$telegram_chatid/$telegram_chatid/g" $configfile
sed -i "s/\$webuser/$webuser/g" $configfile
sed -i "s/\$webpass/$webpass/g" $configfile
sed -i "s/\$webport/$webport/g" $configfile
sed -i "s/\$ipaddress/$ipaddress/g" $configfile
sed -i "s/\$secretkey/$secretkey/g" $configfile

echo starting freqtrade
systemctl start $botname.service
