#!/bin/bash

echo setting variables
configfile=/usr/local/$botname/config.json
readconfig () {cat $configfile}

echo saving current configuration
stake_currency=$(readconfig | jq -cr '.stake_currency')
display_currency=$(readconfig | jq -cr '.fiat_display_currency')
stake_amount=$(readconfig | jq -cr '.stake_amount')
max_open_trades=$(readconfig | jq -cr '.max_open_trades')
exchange_name=$(readconfig | jq -cr '.exchange | .name')
exchange_key=$(readconfig | jq -cr '.exchange | .key')
exchange_secret=$(readconfig | jq -cr '.exchange | .secret')
telegram_token=$(readconfig | jq -cr '.telegram | .token')
telegram_chatid=$(readconfig | jq -cr '.telegram | .chat_id')
webuser=$(readconfig | jq -cr '.api_server | .username')
webpass=$(readconfig | jq -cr '.api_server | .password')
webport=$(readconfig | jq -cr '.api_server | .listen_port')
ipaddress=$(readconfig | jq -cr '.api_server | .listen_ip_address')
secretkey=$(readconfig | jq -cr '.api_server | .jwt_secret_key')

echo
echo Stake Curency: $stake_currency
echo Display Currency: $display_currency
echo Stake Amount: $stake_amount
echo Max Open Trades: $max_open_trades
echo Exchange Name: $exchange_name
echo Exchange Key: $exchange_key
echo Exchange Secret: $exchange_secret
echo Telegram Token: $telegram_token
echo Telegram Chat ID: $telegram_chatid
echo FreqUI Username: $webuser
echo FreqUI Password: $webpass
echo Listen Port: $webport
echo Listen IP Address: $ipaddress
echo Secret Key: $secretkey
echo

echo stopping freqtrade
systemctl stop $botname.service

echo removing old configuration
rm $configfile

echo downloading updated configuration
wget -q https://raw.githubusercontent.com/aristosv/freqtrade/main/install_config --output-document="$configfile"

echo writing saved configuration
echo "$(jq '.stake_currency = $stake_currency' $configfile)" > $configfile
echo "$(jq '.fiat_display_currency = $display_currency' $configfile)" > $configfile
echo "$(jq '.stake_amount = $stake_amount' $configfile)" > $configfile
echo "$(jq '.max_open_trades = $max_open_trades' $configfile)" > $configfile
echo "$(jq '.exchange | .name = $exchange_name' $configfile)" > $configfile
echo "$(jq '.exchange | .key = $exchange_key' $configfile)" > $configfile
echo "$(jq '.exchange | .secret = $exchange_secret' $configfile)" > $configfile
echo "$(jq '.telegram | .token = $telegram_token' $configfile)" > $configfile
echo "$(jq '.telegram | .chat_id = $telegram_chatid' $configfile)" > $configfile
echo "$(jq '.api_server | .username = $webuser' $configfile)" > $configfile
echo "$(jq '.api_server | .password = $webpass' $configfile)" > $configfile
echo "$(jq '.api_server | .listen_port = $webport' $configfile)" > $configfile
echo "$(jq '.api_server | .listen_ip_address = $ipaddress' $configfile)" > $configfile
echo "$(jq '.api_server | .jwt_secret_key = $secretkey' $configfile)" > $configfile

echo starting freqtrade
systemctl start $botname.service
