#!/bin/bash

cd /usr/local/$botname
echo updating freqtrade
printf 'y\ny\n' | ./setup.sh --update

echo updating freqUI
source .env/bin/activate
freqtrade install-ui
deactivate

echo restarting freqtrade
systemctl restart $botname.service
