#!/bin/bash

echo installing prerequisites
apt-get install -y git python3-pip python3-venv sudo

echo cloning repository
git clone https://github.com/freqtrade/freqtrade.git

echo changing directory
cd /root/freqtrade

echo checking out git repository
git checkout develop

echo installing freqtrade bot
printf 'y\ny\n' | ./setup.sh --install
