#!/bin/bash

readconfig () {
 cat /usr/local/$botname/config.json
}

stake_amountbot_name=$(basename "$PWD")
max_open_trades=$(readconfig | jq -cr '.max_open_trades')
stake_currency=$(readconfig | jq -cr '.stake_currency')
stake_amount=$(readconfig | jq -cr '.stake_amount')
fiat_display_currency=$(readconfig | jq -cr '.fiat_display_currency')
exchange_name=$(readconfig | jq -cr '.exchange | .name')
exchange_key=$(readconfig | jq -cr '.exchange | .key')
exchange_secret=$(readconfig | jq -cr '.exchange | .secret')
listen_ip_address=$(readconfig | jq -cr '.api_server | .listen_ip_address')
listen_port=$(readconfig | jq -cr '.api_server | .listen_port')
secret_key=$(readconfig | jq -cr '.api_server | .jwt_secret_key')
frequi_username=$(readconfig | jq -cr '.api_server | .username')
frequi_password=$(readconfig | jq -cr '.api_server | .password')
telegram_token=$(readconfig | jq -cr '.telegram | .token')
telegram_chat_id=$(readconfig | jq -cr '.telegram | .chat_id')

echo Bot Name: $bot_name
echo Max Open Trades: $max_open_trades
echo Stake Curency: $stake_currency
echo Stake Amount: $stake_amount
echo Fiat Display Currency: $fiat_display_currency
echo Exchange Name: $exchange_name
echo Exchange Key: $exchange_key
echo Exchange Secret: $exchange_secret
echo Listen IP Address: $listen_ip_address
echo Listen Port: $listen_port
echo Secret Key: $secret_key
echo FreqUI Username: $frequi_username
echo FreqUI Password: $frequi_password
echo Telegram Token: $telegram_token
echo Telegram Chat ID: $telegram_chat_id

sed -i "s/\$max_open_trades/$max_open_trades/" /usr/local/$botname/config.json
