#!/bin/bash

cd /usr/local/$botname
echo updating freqtrade
echo "y n n" | ./setup.sh -u

echo updating freqUI
source .env/bin/activate
freqtrade install-ui
deactivate

echo restarting freqtrade
systemctl restart $botname.service
