#!/bin/bash

echo installing prerequisites
apt-get install -y git python3-pip python3-venv sudo jq

echo cloning repository
git clone https://github.com/freqtrade/freqtrade.git /usr/local/$botname

echo going to $botname directory
cd /usr/local/$botname

echo checking out git repository
git checkout develop

echo installing freqtrade
printf 'y\ny\n' | ./setup.sh --install

echo installing frequi
source .env/bin/activate
freqtrade install-ui
deactivate
