#!/bin/bash

echo creating freqtrade update script
bash -c "cat > /root/$botname/freqtradeUpdate" << EOL
#!/bin/bash

cd /root/$botname
./setup.sh --update
systemctl restart $botname.service
EOL
chmod +x /root/$botname/freqtradeUpdate

echo creating freqtradeUpdate cron job
bash -c "cat > /etc/cron.d/freqtradeUpdate" << EOL
0 1 * * * root /root/$botname/freqtradeUpdate
EOL

echo creating freqUI update script
bash -c "cat > /root/$botname/freqUIUpdate" << EOL
#!/bin/bash

cd /root/$botname
source .env/bin/activate
freqtrade install-ui
deactivate
EOL
chmod +x /root/$botname/freqUIUpdate

echo creating freqUIUpdate cron job
bash -c "cat > /etc/cron.d/freqUIUpdate" << EOL
0 2 * * * root /root/$botname/freqUIUpdate
EOL
