#!/bin/bash

echo creating freqtrade update script
bash -c "cat > /root/$botname/freqtradeUpdate" << EOL
#!/bin/bash

cd /root/$botname
echo updating freqtrade
printf 'y\ny\n' | ./setup.sh --update

echo updating freqUI
source .env/bin/activate
freqtrade install-ui
deactivate

echo restarting freqtrade
systemctl restart $botname.service
EOL
chmod +x /root/$botname/freqtradeUpdate

echo creating freqtradeUpdate cron job
bash -c "cat > /etc/cron.d/freqtradeUpdate" << EOL
0 1 * * * root /root/$botname/freqtradeUpdate
EOL
